name: Publish to NuGet

on:
  workflow_dispatch:
  release:
    types: [published]

env:
  PROJECT_FILE: src/ImgForge/ImgForge.csproj
  TEST_PROJECT: tests/ImgForge.Tests/ImgForge.Tests.csproj
  PACK_OUTPUT: artifacts/package/release

jobs:
  build:
    permissions:
      contents: read
      id-token: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup dotnet
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 10.0.x

      - name: Restore dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build "${{ env.PROJECT_FILE }}" --configuration Release --no-restore

      - name: Build tests
        run: dotnet build "${{ env.TEST_PROJECT }}" --configuration Release

      - name: Install Playwright browsers
        run: pwsh tests/ImgForge.Tests/bin/Release/net10.0/playwright.ps1 install --with-deps chromium

      - name: Test
        run: dotnet test "${{ env.TEST_PROJECT }}" --configuration Release --no-restore

      - name: Pack
        run: dotnet pack "${{ env.PROJECT_FILE }}" --configuration Release --no-build --no-restore --output "${{ env.PACK_OUTPUT }}"

      - name: NuGet login (OIDC -> temp API key)
        uses: NuGet/login@v1
        id: login
        with:
          user: ${{ secrets.NUGET_USER }}

      - name: Push to NuGet
        if: ${{ github.event_name == 'release' && github.event.action == 'published' && github.event.release.tag_name != '' }}
        shell: pwsh
        run: |
          Get-ChildItem "${{ env.PACK_OUTPUT }}" -Filter *.nupkg |
          ForEach-Object {
            dotnet nuget push $_.FullName `
              --api-key "${{ steps.login.outputs.NUGET_API_KEY }}" `
              --source https://api.nuget.org/v3/index.json
          }
